### ISSUE TITLE
ws and wd convert to u,v

### ISSUE THREAD

**Issue by zhijzhou** [lkugler/wrf_profile#1]
i notice that there is no units of wind speed. In wyoming data the unit of wind speed is 'knot'. But in input sounding of wrf the unit is 'm/s'

**Comment by lkugler** [comment]
Yes, WRF expects m/s and `create_wrf_profiles.py` also expects m/s in the input profile.
The `convert_uwyo_WRF.py` missed a conversion from knot to m/s. Is now updated: #https://github.com/lkugler/wrf_profile/commit/dc7b00eed453c73fbd9259ac50c4886d4608400a
